import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/composents/sidebar";
import SearchBar from "@/composents/searchbar";
import logo from "../assets/logo.png";
import ProviderWrapper from "../composents/ProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ backgroundColor: "#FEF7F2" }}
      >
        <ProviderWrapper>
          {/* Header sticky, responsive */}
          <header className="sticky top-0 z-40 bg-[#FEF7F2]/95 backdrop-blur supports-[backdrop-filter]:backdrop-blur border-b border-black/5">
            <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-3 sm:py-4">
              <div className="flex flex-col gap-3 md:flex-row md:items-center">
                <div className="flex items-center justify-between">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={logo.src}
                    alt="Logo"
                    className="h-8 w-auto sm:h-10"
                  />
                </div>
                <div className="md:ml-6 flex-1 min-w-0">
                  <SearchBar />
                </div>
              </div>
            </div>
          </header>

          {/* Layout responsive: sidebar à gauche en ≥lg, empilé en mobile */}
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-6 sm:py-8">
            <div className="lg:grid lg:grid-cols-[260px_1fr] lg:gap-6">
              {/* Sidebar desktop */}
              <aside className="hidden lg:block">
                <Sidebar />
              </aside>

              {/* Contenu */}
              <main className="min-w-0">{children}</main>
            </div>

            {/* Sidebar mobile: sous le contenu */}
            <aside className="mt-6 lg:hidden">
              <Sidebar />
            </aside>
          </div>
        </ProviderWrapper>
      </body>
    </html>
  );
}