import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/composents/sidebar";
import SearchBar from "@/composents/searchbar";
import logo from "../assets/logo.png"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ backgroundColor: "#FEF7F2" }}
      >
        <div className="sticky top-0 z-40 bg-[#FEF7F2]">
           <div className="absolute top-0 right-0 ">
          <img src={logo.src} alt="Logo" className="h-10 w-auto" />
        </div>
        {/* SearchBar centrée et compacte */}
        <div className="flex justify-center mt-8 ">
          <SearchBar />
        </div>

        </div>

       
        <Sidebar />
 
        {children}
      </body>
    </html>
  );
}
